### ISSUE TITLE
3Dmol.js 1.5 update

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/oc-web-components#157]
They just made an updated release, we should move to it and ensure all current features work. We should also look at whether we can make use of the volume rendering that was added last year. It should use the same cubes we are using for isosurfaces, and I can dig up some old examples for passing in opacity/color points that hopefully made it in too.

**Comment by cryos** [comment]
Does #161 also do this @alesgenova?

**Comment by alesgenova** [comment]
> Does #161 also do this @alesgenova?

Yes, it does, volume rendering is only available in 3dmoljs 1.5+

**Comment by cryos** [comment]
I figured - I want to make sure this gets closed too once it is merged.
